import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"
import "./app.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
        <body className={inter.className}>
          <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
          </body>
    </html>
  );
}
